#!/usr/bin/env bash
# -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
# shellcheck shell=bash

if ! TESTS_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
    echo >&2 "Error fetching tests directory."
    exit 1
fi
readonly TESTS_DIRECTORY

# shellcheck source=./testing-support-lib
source "${TESTS_DIRECTORY}/testing-support-lib"

# ------------------------------------------------------------------------------
# List Tasks Valid Project Snapshot Test Case
function test_list_tasks_valid_project() {
    execute_and_assert_exit_code_and_snapshot 0
}

function snapshot_list_tasks_valid_project() {
    # shellcheck disable=SC2154
    cd "${VALID_PROJECT_DIRECTORY1}" && _mycmd myproject list-tasks
}

function filter_list_tasks_valid_project() {
    # shellcheck disable=SC2154
    sed "s%${TEST_DATA_DIRECTORY}%TEST_DATA_DIRECTORY%"
}

# ------------------------------------------------------------------------------
# List Tasks Valid Project No Tasks Snapshot Test Case
function test_list_tasks_valid_project_no_tasks() {
    execute_and_assert_exit_code_and_snapshot 0
}

function snapshot_list_tasks_valid_project_no_tasks() {
    # shellcheck disable=SC2154
    cd "${VALID_PROJECT_DIRECTORY4}" && _mycmd myproject list-tasks
}

function filter_list_tasks_valid_project_no_tasks() {
    # shellcheck disable=SC2154
    sed "s%${TEST_DATA_DIRECTORY}%TEST_DATA_DIRECTORY%"
}

# ------------------------------------------------------------------------------
# List Tasks Invalid Project Snapshot Test Case
function test_list_tasks_invalid_project() {
    execute_and_assert_exit_code_and_snapshot 1
}

function snapshot_list_tasks_invalid_project() {
    # shellcheck disable=SC2154
    cd "${INVALID_NO_TASK_DEFINITION_DIRECTORY}" && _mycmd myproject list-tasks
}

function filter_list_tasks_invalid_project() {
    sed 's/^\[[^]]*\]/[TIMESTAMP]/'
}

# ------------------------------------------------------------------------------
# List Tasks Invalid Project Failing Loading All Snapshot Test Case
function test_list_tasks_invalid_project_failing_loading_all() {
    execute_and_assert_exit_code_and_snapshot 1
}

function snapshot_list_tasks_invalid_project_failing_loading_all() {
    # shellcheck disable=SC2154
    cd "${VALID_PROJECT_DIRECTORY3}" && _mycmd myproject list-tasks
}

function filter_list_tasks_invalid_project_failing_loading_all() {
    sed \
        -e 's/^\[[^]]*\]/[TIMESTAMP]/' \
        -e "s%${TEST_DATA_DIRECTORY}%TEST_DATA_DIRECTORY%"
}

# ------------------------------------------------------------------------------
# Clean up after every test
function tearDown() {
    cd "${TESTS_DIRECTORY}" || true
}

# ------------------------------------------------------------------------------
# Test Suite Setup
function oneTimeSetUp() {
    copy_test_source_data
}

function oneTimeTearDown() {
    cleanup_test_data
}

# shellcheck disable=SC2154 source=../vendor/shunit2
. "${TESTING_VENDOR_DIRECTORY}/shunit2"
